import { Transaction } from "@/src/types";

export const TRANSACTIONS:Transaction[] = [
  {
    id: 1,
    customerFullname: "John Doe",
    type: "deposit",
    date: "2025-01-03",
    amount: 250000,
    status: "completed",
  },
  {
    id: 2,
    customerFullname: "Mary Johnson",
    type: "withdraw",
    date: "2025-01-04",
    amount: 50000,
    status: "pending",
  },
  {
    id: 3,
    customerFullname: "Ahmed Bello",
    type: "deposit",
    date: "2025-01-05",
    amount: 120000,
    status: "completed",
  },
  {
    id: 4,
    customerFullname: "Sarah Williams",
    type: "withdraw",
    date: "2025-01-05",
    amount: 30000,
    status: "failed",
  },
  {
    id: 5,
    customerFullname: "Daniel Okoye",
    type: "deposit",
    date: "2025-01-06",
    amount: 80000,
    status: "completed",
  },
  {
    id: 6,
    customerFullname: "Emily Brown",
    type: "withdraw",
    date: "2025-01-07",
    amount: 150000,
    status: "completed",
  },
  {
    id: 7,
    customerFullname: "Michael Smith",
    type: "deposit",
    date: "2025-01-08",
    amount: 400000,
    status: "pending",
  },
  {
    id: 8,
    customerFullname: "Grace Chen",
    type: "withdraw",
    date: "2025-01-09",
    amount: 60000,
    status: "completed",
  },
  {
    id: 9,
    customerFullname: "Peter Adams",
    type: "deposit",
    date: "2025-01-10",
    amount: 95000,
    status: "completed",
  },
  {
    id: 10,
    customerFullname: "Aisha Mohammed",
    type: "withdraw",
    date: "2025-01-11",
    amount: 20000,
    status: "failed",
  },
  {
    id: 11,
    customerFullname: "Samuel Turner",
    type: "deposit",
    date: "2025-01-12",
    amount: 175000,
    status: "completed",
  },
  {
    id: 12,
    customerFullname: "Olivia Martinez",
    type: "withdraw",
    date: "2025-01-13",
    amount: 90000,
    status: "pending",
  },
  {
    id: 13,
    customerFullname: "Ibrahim Musa",
    type: "deposit",
    date: "2025-01-14",
    amount: 300000,
    status: "completed",
  },
  {
    id: 14,
    customerFullname: "Linda Green",
    type: "withdraw",
    date: "2025-01-15",
    amount: 45000,
    status: "completed",
  },
  {
    id: 15,
    customerFullname: "Victor Hugo",
    type: "deposit",
    date: "2025-01-16",
    amount: 220000,
    status: "completed",
  },
  {
    id: 16,
    customerFullname: "Chiamaka Eze",
    type: "withdraw",
    date: "2025-01-17",
    amount: 70000,
    status: "failed",
  },
  {
    id: 17,
    customerFullname: "Robert King",
    type: "deposit",
    date: "2025-01-18",
    amount: 130000,
    status: "pending",
  },
  {
    id: 18,
    customerFullname: "Fatima Ali",
    type: "withdraw",
    date: "2025-01-19",
    amount: 110000,
    status: "completed",
  },
  {
    id: 19,
    customerFullname: "James Wilson",
    type: "deposit",
    date: "2025-01-20",
    amount: 500000,
    status: "completed",
  },
  {
    id: 20,
    customerFullname: "Sophia Laurent",
    type: "withdraw",
    date: "2025-01-21",
    amount: 35000,
    status: "pending",
  },
];
